# Generated by Django 4.2.3 on 2023-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0005_newspaper"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsPaper",
            new_name="Newsletter",
        ),
    ]
